name: build

on: push

permissions:
  contents: write

jobs:
  build-for-normal:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout from neutron
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Make Neutron App
        run: npm install && npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build@${{ matrix.os }}
          path: out/make

  build-for-macos-intel:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout from neutron
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Make Neutron App
        run: npm install && npm run make-intel

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build@${{ matrix.os }}@intel
          path: out/make